/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#5d4201',
        'secondary': '#6a5d43',
        'on-primary-fixed': '#261900',
        'on-background': '#1b1c1c',
        'primary-fixed-dim': '#e9c176',
        'surface-dim': '#dcd9d9',
        'outline-variant': '#d1c5b4',
        'surface-tint': '#775a19',
        'inverse-primary': '#e9c176',
        'surface-variant': '#e4e2e1',
        'primary-container': '#c5a059',
        'tertiary-fixed-dim': '#c9c6c1',
        'on-tertiary-fixed': '#1c1c18',
        'on-secondary-fixed': '#231a06',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-container': '#4e3700',
        'on-primary': '#ffffff',
        'on-secondary-container': '#6e6147',
        'on-surface-variant': '#4e4639',
        'surface-container-highest': '#e4e2e1',
        'primary': '#775a19',
        'primary-fixed': '#ffdea5',
        'error': '#ba1a1a',
        'surface-container-low': '#f6f3f2',
        'inverse-on-surface': '#f3f0f0',
        'tertiary': '#5f5e5a',
        'tertiary-container': '#a7a5a0',
        'secondary-fixed': '#f3e0c0',
        'inverse-surface': '#303030',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#e5e2dc',
        'on-tertiary-container': '#3b3b37',
        'outline': '#7f7667',
        'secondary-container': '#f0debd',
        'on-secondary-fixed-variant': '#51452d',
        'surface-container': '#f0eded',
        'secondary-fixed-dim': '#d6c4a5',
        'on-surface': '#1b1c1c',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'surface-container-high': '#eae8e7',
        'background': '#fbf9f8',
        'surface-bright': '#fbf9f8',
        'surface': '#fbf9f8',
        'on-tertiary-fixed-variant': '#474743',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-margin-desktop': '80px',
        'base': '8px',
        'container-margin-mobile': '24px',
        'section-gap-desktop': '96px',
        'gutter': '16px',
        'section-gap-mobile': '48px',
      },
      fontFamily: {
        'headline-lg-mobile': ['EB Garamond', 'serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'headline-lg': ['EB Garamond', 'serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'label-md': ['Be Vietnam Pro', 'sans-serif'],
        'display-lg': ['EB Garamond', 'serif'],
        'garamond': ['EB Garamond', 'serif'],
        'vietnam': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '500' }],
      },
      boxShadow: {
        'luxury': '0 20px 40px -15px rgba(27,28,28,0.08)',
        'luxury-lg': '0 30px 60px -12px rgba(27,28,28,0.08)',
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scaleUp: {
          from: { transform: 'scale(0.95)' },
          to: { transform: 'scale(1)' },
        },
        floating: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        progressFill: {
          from: { width: '0%' },
          to: { width: '100%' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 1.2s cubic-bezier(0.22,1,0.36,1) forwards',
        'scale-up': 'scaleUp 2.5s cubic-bezier(0.22,1,0.36,1) forwards',
        'floating': 'floating 6s ease-in-out infinite',
        'progress-fill': 'progressFill 2s ease-out 0.4s forwards',
      },
    },
  },
  plugins: [],
};
